[package]
author = "Xuzhaoqiu Zeng<xzqzeng@gmail.com>"
description = "Temperature control using stm32f303 for OT"
name = "temp-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
